### PR TITLE
Increase connection timeout

### PR DESCRIPTION
**Pull request by sergioaugrod**
I suggest increase the timeout to 1000ms to avoid connection problems. When are connecting to other regions is common timeout exceed 100ms.

### CODE REVIEW

**Comment by yeongsheng-tan** [comment]
:+1:  Plus 1 from me. Esp. useful for remote broker connections with high latencies.

**Comment by suvash** [comment]
@sergioaugrod @yeongsheng-tan any chances you are using this for prod. ? I had initially planned to make the timeout value parameterized as an optional argument, but haven't gotten around doing it.

**Comment by sergioaugrod** [comment]
@suvash I use in my IoT private projects. I can improve my PR and make the timeout value parameterized.

**Comment by suvash** [comment]
@sergioaugrod I'll have to close this for now.

**Pull request closed without merging**
